name: Validate for HACS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate-hassfest:
    name: hassfest action
    runs-on: "ubuntu-latest"
    steps:
        - name: check out
          uses: "actions/checkout@v2"
        - name: hassfest validation
          uses: "home-assistant/actions/hassfest@master"
